# Generated by Django 5.1.2 on 2025-06-24 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_agh', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
