# Generated by Django 5.1.2 on 2025-06-27 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_agh', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsole',
            name='connection_path',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adv', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_agh.systemsole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
