# Generated by Django 5.1.2 on 2025-06-29 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_agh', '0004_systemsole_connection_path_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='adv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_agh.systemsole'),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
